application: tgtoev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: mainpage.application
  login: required

libraries:
- name: webapp2
  version: latest