application: tgtoev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: mainpage.application
  login: required

- url: /toggldata
  script: mainpage.application
  login: admin

libraries:
- name: webapp2
  version: latest